修复seekTo后无论之前是什么状态，都会开始播放弹幕的问题
KwaiAppTeam/AkDanmaku pull request #15
Opened 2021-12-05 09:04 UTC by SkyD666

2021-12-05 14:36 UTC, SkyD666 commented
详情问题请见#8

2021-12-30 03:57 UTC, xanahopper commented on library/src/main/java/com/kuaishou/akdanmaku/ext/EngineExt.kt
> +internal var DanmakuEntitySystem.waitToSeekLayout: Boolean
这个改法过于 tricky 了，而且也没有其他使用到这个属性的地方，考虑去掉？或者由业务方自己维护？

2021-12-30 03:58 UTC, xanahopper requested changes
移除没有必要的 `waitToSeekLayout`

2021-12-30 15:06 UTC, SkyD666 commented on library/src/main/java/com/kuaishou/akdanmaku/ext/EngineExt.kt
> +internal var DanmakuEntitySystem.waitToSeekLayout: Boolean
已将DanmakuEntitySystem.waitToSeekLayout扩展属性移除

2021-12-30 15:15 UTC, xanahopper commented on library/src/main/java/com/kuaishou/akdanmaku/utils/DanmakuTimer.kt
> +  var waitToSeekLayout = false
此处是否有更好的做法，以及此标志位的意义？

2021-12-30 15:20 UTC, SkyD666 commented on library/src/main/java/com/kuaishou/akdanmaku/utils/DanmakuTimer.kt
> +  var waitToSeekLayout = false
此变量的含义是标志执行seek后有没有重新在屏幕上画一次弹幕（我看到LayoutSystem文件里的update方法，如果是pause状态下不会在屏幕上画弹幕，因此在暂停状态下seek后屏幕将没有弹幕）。如果这个变量是true，就说明需要画一次弹幕。如果单纯不使用这个变量的话，那么在暂停状态下seek后，屏幕会没有弹幕，只有在再次调用start后才会在屏幕上布局弹幕

2021-12-30 15:32 UTC, SkyD666 commented on library/src/main/java/com/kuaishou/akdanmaku/utils/DanmakuTimer.kt
> +  var waitToSeekLayout = false
也就是说waitToSeekLayout这个变量是解决在pause状态下seek后没有立即布局弹幕的问题（屏幕上会没有弹幕，只有在再次开始播放后才会出现弹幕）

2021-12-30 15:38 UTC, xanahopper commented on library/src/main/java/com/kuaishou/akdanmaku/utils/DanmakuTimer.kt
> +  var waitToSeekLayout = false
但是我没有看到任何对这个变量的引用？
我隐约记得这个类似问题我解决过，核心的思想还是需要 engine 在暂停状态下根据是否 dirty 需要绘制一帧内容

2021-12-30 15:43 UTC, SkyD666 commented on library/src/main/java/com/kuaishou/akdanmaku/utils/DanmakuTimer.kt
> +  var waitToSeekLayout = false
LayoutSystem文件的136和137行用到了

2021-12-30 15:46 UTC, xanahopper commented on library/src/main/java/com/kuaishou/akdanmaku/utils/DanmakuTimer.kt
> +  var waitToSeekLayout = false
https://github.com/KwaiAppTeam/AkDanmaku/blob/48c0af485b093593e944581ef57da730ff2d7258/library/src/main/java/com/kuaishou/akdanmaku/ui/DanmakuPlayer.kt#L121-L148
需要解决的是，在暂停后的 Seek 将这里被暂停的流程触发一帧绘制即可

2021-12-30 15:48 UTC, xanahopper commented on library/src/main/java/com/kuaishou/akdanmaku/utils/DanmakuTimer.kt
> +  var waitToSeekLayout = false
> LayoutSystem文件的136和137行用到了

我看到了，我继续考虑一下这里有没有更优雅的实现方式

2021-12-30 15:52 UTC, SkyD666 commented on library/src/main/java/com/kuaishou/akdanmaku/utils/DanmakuTimer.kt
> +  var waitToSeekLayout = false
确实这个变量不太优雅，需要考虑更好的方案

2024-01-23 15:03 UTC, closed without merging